### ISSUE TITLE
Vega animation

### ISSUE THREAD

**Issue by somedaygone** [PBI-David/Deneb-Showcase#1]
You are posting a lot of nice animations here. Have you done anything like these? 

https://observablehq.com/@d3/stacked-to-grouped-bars
(This is animating the radio button, but ideally the user would click to switch the views)

https://archive.nytimes.com/www.nytimes.com/interactive/2013/05/25/sunday-review/corporate-taxes.html?_r=0 
(Toggle "The Overall Picture" and "The View by Industry")

They are on my to-do list after a variance chart like yours. I've read that Vega can't do animation like this, but your samples make me wonder.

**Comment by PBI-David** [comment]
Hi @somedaygone 

Glad you like them😄 .

Vega currently has very limited animation capabilities. The ones I have written are essentially hacks either created by using a timer to move symbols around (fireworks) or using the force transform in combination with a timer to move symbols around (the S&P plot). Your examples look great but I don't think it is possible to create either of them with current functionality. However, I do know that animation is something they're looking at in Vega-Lite and you can read more about it here: http://vis.csail.mit.edu/pubs/animated-vega-lite/
