### ISSUE TITLE
PowerBI - Gantt Chart Specification Error

### ISSUE THREAD

**Issue by maciejsulek** [PBI-David/Deneb-Showcase#2]
Hello, David. 

I ran into a problem while using your Gantt Chart template. 

Specifically, remapping the 'completion' field results in the following error: Expression parse error: (datum['completion']Label). 

I did try remapping your dummy data and fresh data - in both cases the moment I remap this field in PowerBI, the visual throws an error. 

Thanks for your continued support!

**Comment by PBI-David** [comment]
That seems like a Deneb bug. I'll raise the issue there.
 
Don't use the mapping field functionality in Deneb but open the code and make the changes as required. For some reason lines like 738 which are originally

```
 "text": {
                "signal": "datum.completionLabel"
              },

```

are replaced with 

```

"text": {
                "signal": "datum['completion']Label"
              },

```

which doesn't exist.

**Comment by maciejsulek** [comment]
I see! - Thank you for the prompt response.
